export { default as ClaimInfoTab } from './ClaimInfoTab'
export { default as PnLTab } from './PnLTab'
export { default as TimelineTab } from './TimelineTab'
export { default as PaymentsTab } from './PaymentsTab'
export { default as InsuranceInvoiceTab } from './InsuranceInvoiceTab'
export { default as ExpensesTab } from './ExpensesTab'
export { default as DocumentsTab } from './DocumentsTab'
export { default as PartsTab } from './PartsTab'
export { default as POTab } from './POTab'
export { default as SupplierInvTab } from './SupplierInvTab'
export type { ClaimTabProps } from './types'
